package com.djamware.springmvc;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumCheckCreateTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumCheckCreateTest() {
    driver.get("http://localhost:8080/create");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.name("prodName")).click();
    driver.findElement(By.name("prodName")).sendKeys("iphone");
    driver.findElement(By.name("prodDesc")).sendKeys("Smartphone");
    driver.findElement(By.name("prodPrice")).sendKeys("700");
    driver.findElement(By.name("prodImage")).sendKeys("https://images.lojaiplace.com.br/imagens/small/iphone-11-apple-preto-6_z_small.jpg");
    driver.findElement(By.name("saveButton")).click();
  }
}
